# Generated by Django 5.1.4 on 2024-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_advuser_fio_advuser_patronymic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Тариф')),
            ],
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='is_activated',
        ),
    ]
